### ISSUE TITLE
Reorganize riptide-spring-boot-starter module

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#431]
## Context

https://github.com/spring-projects/spring-boot/wiki/Building-On-Spring-Boot
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming

## Possible Implementation

- [x] Move implementations from starter to appropriate modules, e.g.
  - [x] metrics listener to `riptide-failsafe`, see #429 
  - [x] `GzippingHttpRequestInterceptor` to `riptide-httpclient`, see #433 
  - [x] `PluginInterceptors` to `riptide-core`, see #434
- [x] Create new module `riptide-spring-boot-autoconfigure`
  - [x] package `org.zalando.riptide.autoconfigure`
  - [x] Move code from starter there
  - ~[ ] Leave every *stable* API there, but mark it as deprecated~
  - ~[ ] Create new interfaces in autoconfigure, e.g. `HttpClientCustomizer`, and let the old one extend the new one~
  - ~[ ] Hollow out `RiptideAutoConfiguration` and add `@ImportAutoConfiguration(RiptideAutoConfiguration.class)`~
